version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app
      - /app/node_modules
    command:
        sh -c "npm run start"